In [18]:
import pandas as pd
import os
import shutil

data_folder_path = "../datasets/bukva/trimmed/"
data_csv_path = "../datasets/bukva/annotations.csv"
test_folder_path = "../datasets/bukva_processed/test"
test_csv_path = "../datasets/bukva_processed/test_annotations.csv"

os.makedirs(test_folder_path, exist_ok=True)

# Load the original csv file
df = pd.read_csv(data_csv_path, sep="\t")

df.head()

,attachment_id,user_id,text,begin,end,height,width,train,length
0,df5b08f0-41d1-4572-889c-8b893e71069b,185bd3a81d9d618518d10abebf0d17a8,А,36,76,1920,1080,False,150
1,3d2b6a08-131d-40a9-9533-cf45cefb07fd,9a0784a99ea13a8b06cb103c2c8c7f0f,А,31,63,1920,1080,True,78
2,1915f996-71ed-44ae-9a34-ee1959919238,ca6b767f0cccf093ba737ae2fc4fec3d,А,25,81,1920,1080,True,98
3,bfb2d7ae-0f6c-4e20-b087-0965641d34ff,0ab4f8e463cdded2e59d6001f4e1b487,А,18,47,1080,1920,False,82
4,24936cc5-e5bb-43a3-96b8-2a9b4a6d157f,a95892dae1d320bd8b08cbca6a127cd8,А,6,33,1080,1920,False,40

In [19]:
# Filter test data
test_df = df[df['train'] == False].copy()
test_df.head()

,attachment_id,user_id,text,begin,end,height,width,train,length
0,df5b08f0-41d1-4572-889c-8b893e71069b,185bd3a81d9d618518d10abebf0d17a8,А,36,76,1920,1080,False,150
3,bfb2d7ae-0f6c-4e20-b087-0965641d34ff,0ab4f8e463cdded2e59d6001f4e1b487,А,18,47,1080,1920,False,82
4,24936cc5-e5bb-43a3-96b8-2a9b4a6d157f,a95892dae1d320bd8b08cbca6a127cd8,А,6,33,1080,1920,False,40
5,52a31867-5661-4a33-aeea-416fedc8b029,46dd04a1caa75ed3082b573cb5a3ad26,А,7,38,1920,1080,False,100
7,b20b8829-b443-45e8-8ae0-5a9652ccfdf7,95af8e702c909eee7145c6dc1a3d756b,А,30,78,1280,720,False,82

In [20]:
for index, row in test_df.iterrows():
    file_name = f"{row['attachment_id']}.mp4"

    src = os.path.join(data_folder_path, file_name)
    dst = os.path.join(test_folder_path, file_name)

    if os.path.exists(src):
        shutil.move(src, dst)
    else:
        print(f"Warning: File {file_name} not found in {data_folder_path}")

# Drop the redundant columns
test_df = test_df.drop(columns=['user_id', 'train'])

test_df.to_csv(test_csv_path, sep="\t", index=False)
print(f"Successfully created {test_csv_path} with {len(test_df)} entries.")

Successfully created ../datasets/bukva/test_annotations.csv with 680 entries.

In [21]:
test_df.head()

,attachment_id,text,begin,end,height,width,length
0,df5b08f0-41d1-4572-889c-8b893e71069b,А,36,76,1920,1080,150
3,bfb2d7ae-0f6c-4e20-b087-0965641d34ff,А,18,47,1080,1920,82
4,24936cc5-e5bb-43a3-96b8-2a9b4a6d157f,А,6,33,1080,1920,40
5,52a31867-5661-4a33-aeea-416fedc8b029,А,7,38,1920,1080,100
7,b20b8829-b443-45e8-8ae0-5a9652ccfdf7,А,30,78,1280,720,82